### ISSUE TITLE
How to get current page ? 

### ISSUE THREAD

**Issue by Saltless0** [pycampers/flutter_pdf_viewer#13]
I try to get current page variable but I can't access kotlin code. Can you help me ?

**Comment by devxpy** [comment]
There is no such API yet.

If you want, I will add an `OnPageChange` callback, and a `getCurrentPage()` function.

**Comment by devxpy** [comment]
A bottom slider, kinda like this?
<image src="https://user-images.githubusercontent.com/19492893/51794587-c3fa9d00-21fb-11e9-8493-400b0c1fd243.png"  height=300/>

---

For updating the style on-the-fly, we would need to change up the kotlin stuff, I don't believe this can be done without compositing in pure dart.

You can find the kotlin code at [`android/src/main/kotlin/com/pycampers/flutterpdfviewer/FlutterPdfViewerPlugin.kt`](https://github.com/pycampers/flutter_pdf_viewer/blob/master/android/src/main/kotlin/com/pycampers/flutterpdfviewer/FlutterPdfViewerPlugin.kt).

**Comment by devxpy** [comment]
I wouldn't recommended even trying that.

If you want to have a flutter widget with the PDF viewer, you need to be able to do merge the flutter and android native views together, called compositing. And it's very buggy at the moment. https://github.com/pycampers/flutter_pdf_viewer/issues/1#issuecomment-437602048.

(The Pdfium android library just decides to close shop at some places, and the view totally breaks)

The current (stable) architecture opens up a native android view when you open the pdf. There is no chance of *any* flutter widgets there.

**Comment by Saltless0** [comment]
Thank you for taking care of me . I think you are right. Anyway, Can I request api for get current page and jumpto function. I would be grateful.

**Comment by devxpy** [comment]
Yes, please give me a few days.

**Comment by devxpy** [comment]
You can use [AnalyticsCallback](https://pub.dev/documentation/flutter_pdf_viewer/latest/flutter_pdf_viewer/AnalyticsCallback.html) and [jumpToPage](https://pub.dev/documentation/flutter_pdf_viewer/latest/flutter_pdf_viewer/PdfViewer/jumpToPage.html) features on `0.5.0`.
