### ISSUE TITLE
Add an Usage Section?

### ISSUE THREAD

**Issue by d-apps** [pycampers/flutter_pdf_viewer#17]
Hi pycampers,

Could you please add an Usage section?

I don't understand how to implement your lib.

I can't find FlutterPdfViewer.loadFilePath...

Thank you.

**Comment by devxpy** [comment]
Is the example app provided not enough? https://github.com/pycampers/flutter_pdf_viewer/blob/master/example/lib/main.dart

**Comment by d-apps** [comment]
Sorry, my bad. I didn't see the example folder.

Thank you.
