### ISSUE TITLE
Landscape Mode Crash

### ISSUE THREAD

**Issue by familfamilzade** [pycampers/flutter_pdf_viewer#20]
Hi, 

After loading pdf with loadBytes method, when the phone goes to landscape mode, application crashes with Error Message shown below. I am usin 0.0.9 version of plugin. I tried with 0.2.1 and it behaved the same. Error Log :
E/AndroidRuntime( 1204): FATAL EXCEPTION: Thread-4
E/AndroidRuntime( 1204): Process: com.example.cvgenerator, PID: 1204
E/AndroidRuntime( 1204): java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 4567) from **** (port ****): connect failed: ECONNREFUSED (Connection refused)
E/AndroidRuntime( 1204):        at libcore.io.IoBridge.connect(IoBridge.java:137)
E/AndroidRuntime( 1204):        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
E/AndroidRuntime( 1204):        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
E/AndroidRuntime( 1204):        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
E/AndroidRuntime( 1204):        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
E/AndroidRuntime( 1204):        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
E/AndroidRuntime( 1204):        at java.net.Socket.connect(Socket.java:621)
E/AndroidRuntime( 1204):        at java.net.Socket.connect(Socket.java:570)
E/AndroidRuntime( 1204):        at java.net.Socket.<init>(Socket.java:450)
E/AndroidRuntime( 1204):        at java.net.Socket.<init>(Socket.java:218)
E/AndroidRuntime( 1204):        at com.pycampers.flutterpdfviewer.UtilKt.readBytesFromSocket(util.kt:20)
E/AndroidRuntime( 1204):        at com.pycampers.flutterpdfviewer.PdfActivityThread.buildConfigurator(PdfActivity.kt:62)
E/AndroidRuntime( 1204):        at com.pycampers.flutterpdfviewer.PdfActivityThread.run(PdfActivity.kt:76)
E/AndroidRuntime( 1204): Caused by: android.system.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
E/AndroidRuntime( 1204):        at libcore.io.Linux.connect(Native Method)
E/AndroidRuntime( 1204):        at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:118)
E/AndroidRuntime( 1204):        at libcore.io.IoBridge.connectErrno(IoBridge.java:151)
E/AndroidRuntime( 1204):        at libcore.io.IoBridge.connect(IoBridge.java:129)
E/AndroidRuntime( 1204):        ... 12 more
I/Process ( 1204): Sending signal. PID: 1204 SIG: 9

How can it be solved?

**Comment by devxpy** [comment]
Fixed in `v0.4.0`!

https://github.com/pycampers/flutter_pdf_viewer/blob/288fa872401e35124440eb28c71e5f74fb86303e/android/src/main/AndroidManifest.xml#L5
