### ISSUE TITLE
Is there any option PDF load from  URL ??????

### ISSUE THREAD

**Issue by shailendraweb8** [pycampers/flutter_pdf_viewer#21]

**Comment by devxpy** [comment]
Sorry! But no, It was removed down the line. 
It's out of the context for a pdf viewing library to include a file downloader. It adds unnecessary dependencies and cruft to the project.

I would suggest using something like [http](https://pub.dartlang.org/packages/http) or [dio](https://pub.dartlang.org/packages/dio) to first download the file to a temporary location and then calling
[`PdfViewer.loadFile`](https://pub.dartlang.org/documentation/flutter_pdf_viewer/latest/flutter_pdf_viewer/PdfViewer/loadFile.html).

Sorry for not updating the README to reflect this!
