### ISSUE TITLE
Can we get more analytics?

### ISSUE THREAD

**Issue by ammaratef45** [pycampers/flutter_pdf_viewer#26]
The PDF opens on the page we closed it last time, can we get this info with analytics like showing last_opened_page or something like that?

We can even create a new function for it

**Comment by devxpy** [comment]
The [atExit](https://pub.dev/documentation/flutter_pdf_viewer/latest/flutter_pdf_viewer/PdfViewerConfig/atExit.html) callback should give you the last opened page when the pdf viewer exits.

Or you can use [analyticsCallback](https://pub.dev/documentation/flutter_pdf_viewer/latest/flutter_pdf_viewer/PdfViewer/analyticsCallback.html) for more fine-grained tracking.

**Comment by ammaratef45** [comment]
@devxpy Thanks, `atExit` solved it, however, `analyticsCallback` is never called (I've enabled it)

**Comment by devxpy** [comment]
Okay, please create a new issue for `analyticsCallback`.
