### ISSUE TITLE
Analytics callback not working

### ISSUE THREAD

**Issue by ammaratef45** [pycampers/flutter_pdf_viewer#31]
I've wrote the following code
```
PdfViewer.enableAnalytics(Duration(days: 8));
    PdfViewer.analyticsCallback = (s, i, b) {
      print('analytics string: $s');
      print('analytics int: $i');
      print('analytics bool: $b');
    };
```
but I didn't see any logs from the callback

the output of `flutter analyze`:
>Analyzing example...                                                    
No issues found! (ran in 45.6s)

the output of `flutter doctor -v`:
>[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /opt/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
>[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/ammar/Android/Sdk
    • Android NDK at /home/ammar/Android/Sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/ammar/Portable/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

>[!] Android Studio (version 3.4)
    • Android Studio at /home/ammar/Portable/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

>[!] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /home/ammar/Portable/idea-IC-183.5429.30
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

>[✓] VS Code (version 1.35.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.2.0

>[✓] Connected device (1 available)
    • Moto G 5 Plus • ZY2247QBNC • android-arm • Android 8.1.0 (API 27)

>! Doctor found issues in 2 categories.

**Comment by devxpy** [comment]
Hey, can you try decreasing the duration? Something like a second or so?

**Comment by ammaratef45** [comment]
@devxpy made it 8 seconds but still, nothing is printed.

**Comment by devxpy** [comment]
Okay, let me inspect.

**Comment by devxpy** [comment]
Thanks to https://github.com/pycampers/flutter-plugin-scaffold/pull/1, this should be fixed in `v0.6.1`.

**Comment by devxpy** [comment]
Sidenote: You don't need to supply a duration if you're not using `PdfViewer.analyticsEntries`. I hope the [docs](https://pub.dev/documentation/flutter_pdf_viewer/latest/flutter_pdf_viewer/PdfViewer/enableAnalytics.html) make this clear.

**Comment by ammaratef45** [comment]
@devxpy Thanks
