### ISSUE TITLE
TransactionTooLargeException when calling loadBytes()

### ISSUE THREAD

**Issue by donarn** [pycampers/flutter_pdf_viewer#4]
We have an application that will be processing PDFs encoded as base64-encoded strings.
We plan to display these by calling FlutterPdfViewer.loadBytes(base64Decode(theBase64String).
This works fine for small, simple pdfs, but we get an exception when trying load larger strings representing larger,more complex PDFs.

For example, encoding the 14-page test.pdf file included in the example project to a 1355088-character string (representing 1016315 bytes) and calling loadBytes() on the corresponding byte array throws:

09-07 14:20:02.102 1665-1904/? E/ActivityManager: Transaction too large, intent: Intent { cmp=com.pycampers.flutterpdfviewerexample/com.pycampers.flutterpdfviewer.PdfActivity (has extras) }, extras size: 1016492, icicle size: 0
09-07 14:20:02.107 1665-1904/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1019812)
09-07 14:20:02.207 1665-1904/? E/ActivityManager: Transaction too large, intent: Intent { cmp=com.pycampers.flutterpdfviewerexample/com.pycampers.flutterpdfviewer.PdfActivity (has extras) }, extras size: 1016492, icicle size: 0
09-07 14:20:02.211 1665-1904/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1019812)
09-07 14:20:02.211 1665-1904/? E/ActivityManager: Second failure launching com.pycampers.flutterpdfviewerexample/com.pycampers.flutterpdfviewer.PdfActivity, giving up
    android.os.TransactionTooLargeException: data parcel size 1019812 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:764)
        at android.app.IApplicationThread$Stub$Proxy.scheduleLaunchActivity(IApplicationThread.java:1216)
        at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1457)
        at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:974)
        at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:7152)
        at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:7219)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:291)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2919)
        at android.os.Binder.execTransact(Binder.java:697)

Unfortunately, these PDFs will contain confidential information that cannot rest on the device, so writing the bytes to storage then calling loadFilePath() is not an option.

**Comment by donarn** [comment]
Sorry, I didn't see that caveat.
We'll be receiving the base64-encoded documents over the network from our web API.
Due to confidentiality and privacy regulations, we are not allowed to store the PDF on the device.

**Comment by devxpy** [comment]
Ok,

for now a good solution would be to send XOR encrypted/password protected PDFs from the web API, then store it in a cached location using path_provider plugin.

Since the PDFs are encrypted, confidentiality shouldn't be an issue. 

This plugin has support for decrypting PDFs using `xorDecryptKey` keyword argument.

You can also provide the `password` kwarg if you have used a password protected PDF. 

The plugin itself does in-memory decryption, so the decrypted files don't touch the disk. (Assuming Pdfium Android doesn't do that)

**Comment by donarn** [comment]
Thank you for the prompt response and suggested workarounds.
I'll follow up with our project lead to see if temporarily saving password-protected PDFs is an option that will keep us in compliance.

**Comment by gedw99** [comment]
Why not chunk the response between dart and java ?

Would solve it ?

**Comment by devxpy** [comment]
@gedw99 That is a good solution.

Should be straightforward to implement. It would take quite a bit of time to launch, but should "work".

On a side note, if @donarn really wants to protect the data, he should implement some kind of encryption strategy.

**Comment by gedw99** [comment]
@devxpy Ok glad it helped.

If your thinking of sockets, then maybe jsonrpc is what you MIGHT mean - not sure.
I have been using this between flutter and golang to get things talking using chunking. it uses stream channel underneath.
https://pub.dartlang.org/packages/json_rpc_2

Its yucky thats the image is encoded base64 - huge memory waste i know. 

This feels like a terrible way to do this. Anyway, its late. tired..

**Comment by devxpy** [comment]
@donarn Is it possible for you to share that pdf?

**Comment by donarn** [comment]
i just took the test.pdf file that is included in the example project and base64-encoded it.

[test_dart_chunk_250.txt](https://github.com/pycampers/flutter_pdf_viewer/files/2460607/test_dart_chunk_250.txt)

**Comment by devxpy** [comment]
@donarn Can you please share the full code, including the base64 "decoding" part?

**Comment by donarn** [comment]
decoding is done via the standard base64Decode() function from dart:convert.


[sample.zip](https://github.com/pycampers/flutter_pdf_viewer/files/2460893/sample.zip)
