### ISSUE TITLE
 how to turn  nigthMode?

### ISSUE THREAD

**Issue by glin94** [pycampers/flutter_pdf_viewer#5]
FlutterPdfViewer.loadFilePath ("file://"+_cachedFile.path);

**Comment by devxpy** [comment]
Did you read the API section of the README?

https://github.com/pycampers/flutter_pdf_viewer/blob/master/README.md#api

Does passing `nightMode: true` not work for you?

**Comment by devxpy** [comment]
Closing due to no response
