### ISSUE TITLE
Application is size is getting increase by 19 Mb  

### ISSUE THREAD

**Issue by chhota89** [pycampers/flutter_pdf_viewer#8]
After adding the library the application size is getting increased by 19 Mb. Without library, the apk size is 5.3 Mb and after flutter_pdf_viewer library is added apk size reached to 24 Mb. 

Pubspec.yml file
`name: flutter_movie_app
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  url_launcher: ^3.0.0
  scoped_model: ^0.3.0
  rxdart: ^0.18.1
  flutter_pdf_viewer: ^0.0.4
  http: ^0.12.0

flutter:
    uses-material-design: true
    fonts:
       - family: Merriweather
         fonts:
           - asset: fonts/Merriweather-Regular.ttf
           - asset: fonts/Merriweather-Bold.ttf
           - asset: fonts/Merriweather-Italic.ttf
             style : italic`

**Comment by devxpy** [comment]
You're going to have to take that upstream, sorry.

https://github.com/barteksc/AndroidPdfViewer#why-resulting-apk-is-so-big

**Comment by chhota89** [comment]
any idea what will be the apk size after generating split apk

**Comment by devxpy** [comment]
@chhota89. No idea, I never had an issue with the APK size. 

You might be interested in [open_file](https://pub.dartlang.org/packages/open_file) plugin which opens the pdf in external app, and hence the apk size is minimal.

**Comment by devxpy** [comment]
@chhota89 I tested it out, and the resulting APK size decreased significantly, around 5x less, from ~50MB to ~10MB.
