### ISSUE TITLE
Flutter_test from sdk depends on http 0.11.3+17

### ISSUE THREAD

**Issue by JustLazzah** [pycampers/flutter_pdf_viewer#9]
**Steps to Reproduce:**

Add "flutter_pdf_viewer: ^0.0.4 as dependency breaks the package upgrade.

![errore](https://user-images.githubusercontent.com/40595671/47952477-3565df00-df70-11e8-9363-daec2bb2a219.jpg)

**Comment by devxpy** [comment]
Thanks for the report.

**Comment by devxpy** [comment]
Please try to upgrade flutter using `flutter upgrade`.

I think this is because you have an outdated version in your local environment.
Related issue upstream - https://github.com/flutter/flutter/issues/19881

Thanks

**Comment by JustLazzah** [comment]
I had already seen [flutter/flutter#19881](https://github.com/flutter/flutter/issues/19881) , only that he refers to version 0.5.1 of Flutter, while I am at 0.9.4. Here are the results of 'Upgrade' and 'doctor':
![tempsnip](https://user-images.githubusercontent.com/40595671/47955428-4591b480-df98-11e8-8916-1b22c8651e90.png)

**Comment by devxpy** [comment]
Have you tried removing `flutter_pdf_viewer` from `pubspec.yaml` and then, running `flutter package upgrade`?

That way, it might just upgrade `flutter_test`, and then you can install this plugin.  

If not, we can try to raise an issue upstream. 
(I am quite certain that this is not an issue specifc to this plugin.)

**Comment by JustLazzah** [comment]
Ok, I solved the problem of the upgrade like this: [flutter/issues/115](https://github.com/zino-app/graphql-flutter/issues/115#issuecomment-434675858)

**Comment by devxpy** [comment]
That's great!

For reference, this is what needed to be done -
```
$ flutter update-packages --force-upgrade
```
